mqtt:
  host: 192.168.0.221
  port: 1883
  user: ""
  password: ""
  topic_prefix: boiler_room
  status_topic: status
  status_payload_running: "online" 
  status_payload_stopped: "offline" 
  status_payload_dead: "dead"


gpio_modules:
  - name: raspberrypi
    module: raspberrypi

digital_outputs:
  - name: thermostat
    module: raspberrypi
    pin: 26
    on_payload: "on"
    off_payload: "off"
    initial: low  # This optional value controls the initial state of the pin before receipt of any messages from MQTT. Valid options are 'low' and 'high'.
    retain: no # This option value controls if the message is retained. Default is no.
